### ISSUE TITLE
Question: why use a lazy var in QueueManager

### ISSUE THREAD

**Issue by darioDelTemple** [wibosco/NetworkingInOperations-Example#1]
Hi,
Nice article on Networking layer for an iOS App. 

While looking at the code I came across this in the QueueManager class:
`class QueueManager {

    lazy var queue: OperationQueue = {
        let queue = OperationQueue()

        return queue;
    }()
`

I was wandering, why declare that var as lazy?

**Comment by wibosco** [comment]
I normally use `lazy` to group together the configuration of the property (as I'm not a fan of large init'ers) but in the above property `OperationQueue` isn't being further configured so could just have been:

`let queue = OperationQueue()`

 To be honest, I think I used `lazy` here purely through muscle memory.

**Comment by darioDelTemple** [comment]
okay, sounds fair, I though I was missing something else. Thanks for the answer.
